- Source/QuantityTypes.Tests/Quantities/LengthTests.cs
- Source/QuantityTypes/Operators/Length.cs
Length needs support Length * TypographicResolution.
> Issue #16: Length needs support Length * TypographicResolution.

- Source/QuantityTypes/Operators/Capacitance.cs
- Source/QuantityTypes/Operators/ElectricCharge.cs
- Source/QuantityTypes/Operators/ElectricCurrent.cs
- Source/QuantityTypes/Operators/ElectricVoltage.cs
- Source/QuantityTypes/Operators/Power.cs
- Source/QuantityTypes/Operators/Time.cs
- Source/QuantityTypes/Quantities/ElectricCharge.cs
- Source/QuantityTypes/Quantities/ElectricCurrent.cs
- Source/QuantityTypes/Quantities/ElectricResistance.cs
- Source/QuantityTypes/Quantities/ElectricVoltage.cs
- Source/QuantityTypes/Quantities/Energy.cs
- Source/QuantityTypes/Quantities/Power.cs
- Source/QuantityTypes/Quantities/Units.csv
- Source/QuantityTypes/QuantityTypes.csproj
Hi, this is my first pull request ever, so I hope I am doing this right - I have added code to simplify calculations with electrical units.
> added unit prefixes and operator overloads for various electrical units

- CHANGELOG.md
- appveyor.yml
> Use GitHub as source server

- Source/QuantityTypes.Tests/Quantities/TemperatureTests.cs
- Source/QuantityTypes/Operators/Temperature.cs
- Source/QuantityTypes/Quantities/Temperature.cs
Merged the changes made to other types into Temperature type while
keeping the particularities of this type. Added an operator. Updated
tests.
> Improvements to Temperature type + adding an operator

- Source/QuantityTypes/Operators/Area.cs
- Source/QuantityTypes/Operators/Energy.cs
- Source/QuantityTypes/Operators/Mass.cs
- Source/QuantityTypes/Operators/Power.cs
- Source/QuantityTypes/Operators/SpecificHeatCapacity.cs
- Source/QuantityTypes/Operators/TemperatureChange.cs
- Source/QuantityTypes/Operators/TemperatureDifference.cs
- Source/QuantityTypes/QuantityTypes.csproj
Adding operators + fixing some whitespace and naming of variables or
comments + forgotten change in QuantityTypes.csproj
> Adding operators

- Source/QuantityTypes.Tests/Quantities/LengthTests.cs
- Source/QuantityTypes/Quantities/Length.cs
- Source/QuantityTypes/Quantities/Units.csv
not sure if the micrometre symbol should be µm or um. I followed the conventions used in the other instances of "microXXX" and used "um".
> add nanometre and micrometre

- CHANGELOG.md
- Source/QuantityTypes.Tests/Quantities/TimeTests.cs
- Source/QuantityTypes/Extensions/TimeExtensions.cs
> Add TimeSpan extension methods

- Source/QuantityTypes.Tests/Quantities/LengthTests.cs
- Source/QuantityTypes/Units.csv
> Consistent micro (u|?) units

- Source/QuantityTypes.Tests/Quantities/LengthTests.cs
- Source/QuantityTypes.Tests/Quantities/TypographicLengthTests.cs
- Source/QuantityTypes/Operators/Length.cs
> Add TypographicResolution operator

- CHANGELOG.md
- Source/QuantityTypes.Tests/Quantities/MomentTests.cs
- Source/QuantityTypes.Tests/QuantityTypes.Tests.csproj
- Source/QuantityTypes/Operators/Moment.cs
- Source/QuantityTypes/Units.csv
> Add moment type

- CHANGELOG.md
- Source/QuantityTypes.Tests/Quantities/DensityTests.cs
- Source/QuantityTypes/Units.csv
> Add t/m^3 unit

- CHANGELOG.md
- Source/CodeGenerator/Template.cs
- Source/QuantityTypes.Tests/Quantities/LengthTests.cs
> Added NaN, PositiveInfinity and NegativeInfinity quantities #83

- Source/QuantityTypes.Tests/JsonTests/NewtonSoftJsonTests.cs
- Source/QuantityTypes.Tests/JsonTests/QuantityJsonConverter.cs
- Source/QuantityTypes.Tests/JsonTests/QuantityJsonConverterTests.cs
- Source/QuantityTypes.Tests/QuantityTypes.Tests.csproj
> Fix null reference execption in QuantityJsonConverter #85

- Source/QuantityTypes/QuantityTypes.xproj
- Source/QuantityTypes/Units.csv
added some units smaller than millisecond
> Add time units

- CHANGELOG.md
- Source/CodeGenerator/Template.cs
- Source/Examples/WpfExample/QuantityConverter.cs
- Source/QuantityTypes.Tests/Quantities/DensityTests.cs
- Source/QuantityTypes.Tests/Quantities/LengthTests.cs
- Source/QuantityTypes/UnitProvider/UnitProvider.cs
> TryParse of  `null` should return `false`

- CHANGELOG.md
- Source/CodeGenerator/CodeGenerator.csproj
- Source/CodeGenerator/Properties/launchSettings.json
- Source/QuantityTypes.Csv.Tests/QuantityTypes.Csv.Tests.csproj
- Source/QuantityTypes.Csv/CsvFile.cs
- Source/QuantityTypes.Csv/QuantityTypes.Csv.csproj
- Source/QuantityTypes.Dynamic.Tests/QuantityTypes.Dynamic.Tests.csproj
- Source/QuantityTypes.Dynamic/QuantityTypes.Dynamic.csproj
- Source/QuantityTypes.Tests/QuantityTypes.Tests.csproj
- Source/QuantityTypes.Tests/XmlTests/XmlSerializationTests.cs
- Source/QuantityTypes.sln
- Source/QuantityTypes/QuantityTypes.csproj
- appveyor.yml
- global.json
> Multi target

- Source/CodeGenerator/CodeGenerator.csproj
- Source/QuantityTypes.Csv.Tests/CsvFileTests.cs
- Source/QuantityTypes.Csv.Tests/CsvParserTests.cs
- Source/QuantityTypes.Dynamic/QuantityTypes.Dynamic.csproj
- appveyor.yml
> Test script

- CHANGELOG.md
- Source/QuantityTypes.Csv/QuantityTypes.Csv.csproj
- Source/QuantityTypes.Dynamic/QuantityTypes.Dynamic.csproj
- Source/QuantityTypes/QuantityTypes.csproj
Change target to netstandard1.3
Remove dependencies to System.Xml.XmlSerializer
> Remove package dependencies

- Source/CodeGenerator/CodeGenerator.csproj
- Source/Examples/PerformanceTest/PerformanceTest.csproj
- Source/QuantityTypes.Csv.Tests/QuantityTypes.Csv.Tests.csproj
- Source/QuantityTypes.Dynamic.Tests/QuantityTypes.Dynamic.Tests.csproj
- Source/QuantityTypes.Tests/QuantityTypes.Tests.csproj
- appveyor.yml
> Upgrade test projects to netcore3.1

- Source/QuantityTypes.Csv/QuantityTypes.Csv.csproj
- Source/QuantityTypes.Dynamic/QuantityTypes.Dynamic.csproj
- Source/QuantityTypes/QuantityTypes.csproj
> remove support for net45

- .github/workflows/ci.yml
- .github/workflows/release-preview.yml
- .github/workflows/release.yml
- CHANGELOG.md
- README.md
- Source/CodeGenerator/CodeGenerator.csproj
- Source/QuantityTypes.Csv.Tests/CsvFileTests.cs
- Source/QuantityTypes.Csv.Tests/CsvTests.cs
- Source/QuantityTypes.Csv.Tests/CsvWriterTests.cs
- Source/QuantityTypes.Csv.Tests/CultureInfos.cs
- Source/QuantityTypes.Csv.Tests/QuantityTypes.Csv.Tests.csproj
- Source/QuantityTypes.Csv/QuantityTypes.Csv.csproj
- Source/QuantityTypes.Dynamic/QuantityTypes.Dynamic.csproj
- Source/QuantityTypes.Tests/Core/UnitProviderTests.cs
- Source/QuantityTypes.Tests/QAssert.cs
- Source/QuantityTypes.Tests/XmlTests/XmlSerializationTests.cs
- Source/QuantityTypes.sln
- Source/QuantityTypes/QuantityTypes.csproj
> Add GitHub workflows for CI, Release and Release preview 

- Source/QuantityTypes/Units.csv
Added the °/s as listed in #120
> Added degrees per second symbol

- CHANGELOG.md
- Source/QuantityTypes.Csv/CsvFile.cs
- Source/QuantityTypes.Csv/QuantityTypes.Csv.csproj
- Source/QuantityTypes.Dynamic/QuantityTypes.Dynamic.csproj
- Source/QuantityTypes/QuantityTypes.csproj
> Netstandard 2.0
